<?php

namespace MarketingBundle\Repository;

/**
 * AddsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddsRepository extends \Doctrine\ORM\EntityRepository
{
}
