<?php

namespace MarketingBundle\Repository;

/**
 * ClaimsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaimsRepository extends \Doctrine\ORM\EntityRepository
{
}
