<?php

namespace MarketingBundle\Repository;

/**
 * NewsFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
