<?php

namespace EcommerceBundle\Repository;

/**
 * LineOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
