<?php

namespace EcommerceBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('orders')
            ->Select('orders')
            ->Where('orders.id IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
}
