# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_BRAND: ROLE_BRAND
        ROLE_BAKERY: ROLE_BAKERY
        ROLE_DELIVERYMAN: ROLE_DELIVERYMAN
        ROLE_USER: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login

            logout:
                path:   /logout
                target: /

            anonymous:    true


#oauth:
            #                resource_owners:
            #                    facebook:           "/login/check-facebook"

#                            login_path:        /connect
 #                           failure_path:      /connect
 #                           oauth_user_provider:
  #                              service: hwi_oauth.user.provider.fosub_bridge
#add redirect after logout here
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, allow_if: "is_anonymous()" }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/brand, role: ROLE_BRAND }
        - { path: ^/bakery, role: ROLE_BAKERY }
        - { path: ^/deliveryMan, role: ROLE_DELIVERYMAN }
        - { path: ^/favorite, role: [ROLE_ADMIN, ROLE_BRAND, ROLE_BAKERY, ROLE_DELIVERYMAN, ROLE_USER] }
        - { path: ^/backoffice, role: [ROLE_ADMIN, ROLE_BRAND, ROLE_BAKERY, ROLE_DELIVERYMAN] }

