<?php

namespace ProductManagementBundle\Repository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersByFavorite($subcategoryId){
        $subcategory = $this->getEntityManager()->find('ProductManagementBundle:SubCategory', $subcategoryId);
        $query = $this->getEntityManager()->createQuery('select f from ProductManagementBundle:Favorite f where f.subcategory = ?1')
            ->setParameter(1, $subcategory);
        $res = $query->getResult();
        $users = array();
        for ($i = 0; $i<count($res); $i++)
        {
            $users[] = $res[$i]->getUser();
        }
        return $users;
    }
}
