<?php

namespace ProductManagementBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMostLikedSubcats(){
        $query = $this->getEntityManager()
            ->createQuery('select c, count(c.id) as HIDDEN counter from ProductManagementBundle:SubCategory c
                                INNER JOIN ProductManagementBundle:Favorite f with c = f.subcategory
                                GROUP BY c.id ORDER by counter DESC ')
            ->setMaxResults(5);
        return $query->getResult();
    }
}
