<?php

namespace BakeryManagementBundle\Repository;

/**
 * BakeryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BakeryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findaddress($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT a.address,a.latitude,a.longitude FROM  BakeryManagementBundle:Bakery a WHERE a.enseigne= :id")
            ->setParameter('id',$id);
        return $q->getResult();
    }
    public function findbak()
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT a.id FROM  BakeryManagementBundle:Bakery a");
        return $q->getResult();
    }

}
